---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ncog-deployment
spec:
  selector:
    matchLabels:
      app: ncog
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ncog
    spec:
      containers:
        - name: ncog
          image: docker.pkg.github.com/khonsulabs/ncog/ncog-webserver:latest
          ports:
            - containerPort: 7878
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: ncog-lb
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "ec3e04f8-0359-4610-b117-eb6fcd7237f9"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/__healthcheck"
spec:
  type: LoadBalancer
  selector:
    app: ncog
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 7878
